"""Tests for cross-instance federation: HTTP Signatures, remote actor resolution, follow-by-handle."""
from __future__ import annotations

import json

from flaskmarks import create_app


class TestHTTPSignatures:
    """Tests for HTTP Signature generation and verification."""

    def test_sign_and_verify_round_trip(self):
        """A signature generated by sign_headers should pass verify_signature."""
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography.hazmat.backends import default_backend

        from flaskmarks.core.http_signatures import sign_headers, verify_signature

        key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend(),
        )
        private_pem = key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        ).decode('utf-8')
        public_pem = key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        ).decode('utf-8')

        key_id = 'https://example.com/actor#main-key'

        headers = sign_headers(
            private_key_pem=private_pem,
            key_id=key_id,
            method='POST',
            path='/inbox',
            host='remote.instance',
        )

        assert 'Date' in headers
        assert 'Signature' in headers
        assert key_id in headers['Signature']

        # Extract the signature from the header
        sig_parts = {}
        for part in headers['Signature'].split(','):
            if '=' in part:
                k, v = part.split('=', 1)
                sig_parts[k.strip()] = v.strip('"')

        result = verify_signature(
            public_key_pem=public_pem,
            method='POST',
            path='/inbox',
            host='remote.instance',
            date=headers['Date'],
            signature_b64=sig_parts['signature'],
        )

        assert result is True

    def test_verify_fails_with_wrong_key(self):
        """Verification with wrong public key should return False."""
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography.hazmat.backends import default_backend

        from flaskmarks.core.http_signatures import sign_headers, verify_signature

        key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend(),
        )
        private_pem = key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        ).decode('utf-8')

        wrong_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend(),
        )
        wrong_public_pem = wrong_key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        ).decode('utf-8')

        headers = sign_headers(
            private_key_pem=private_pem,
            key_id='https://example.com/actor#main-key',
            method='POST',
            path='/inbox',
            host='remote.instance',
        )

        sig_parts = {}
        for part in headers['Signature'].split(','):
            if '=' in part:
                k, v = part.split('=', 1)
                sig_parts[k.strip()] = v.strip('"')

        result = verify_signature(
            public_key_pem=wrong_public_pem,
            method='POST',
            path='/inbox',
            host='remote.instance',
            date=headers['Date'],
            signature_b64=sig_parts['signature'],
        )

        assert result is False


class TestRemoteActorResolution:
    """Tests for remote actor resolution (monkeypatched)."""

    def test_resolve_remote_actor_caches_result(self, monkeypatch):
        """Remote actor resolution caches the result for subsequent calls."""
        import requests
        from flaskmarks.views.federation import resolve_remote_actor, _remote_actor_cache

        _remote_actor_cache.clear()

        actor_url = 'https://remote.instance/users/alice'
        actor_data = {
            '@context': 'https://www.w3.org/ns/activitystreams',
            'id': actor_url,
            'type': 'Person',
            'preferredUsername': 'alice',
            'inbox': f'{actor_url}/inbox',
            'publicKey': {
                'id': f'{actor_url}#main-key',
                'publicKeyPem': '-----BEGIN PUBLIC KEY-----\nFAKE\n-----END PUBLIC KEY-----',
            },
        }

        call_count = 0

        def fake_get(url, **kwargs):
            nonlocal call_count
            call_count += 1
            response = type('FakeResponse', (), {
                'status_code': 200,
                'json': lambda _: actor_data,
            })()
            return response

        monkeypatch.setattr('requests.get', fake_get)

        # First call should hit the network
        result1 = resolve_remote_actor(actor_url)
        assert call_count == 1
        assert result1 is not None
        assert result1['preferredUsername'] == 'alice'

        # Second call should use cache
        result2 = resolve_remote_actor(actor_url)
        assert call_count == 1  # Still 1 - cached!
        assert result2 == result1

    def test_resolve_remote_actor_returns_none_on_failure(self, monkeypatch):
        """Remote actor resolution returns None for non-200 responses."""
        import requests
        from flaskmarks.views.federation import resolve_remote_actor, _remote_actor_cache

        _remote_actor_cache.clear()

        def fake_get(url, **kwargs):
            response = type('FakeResponse', (), {
                'status_code': 404,
                'json': lambda _: {},
            })()
            return response

        monkeypatch.setattr('requests.get', fake_get)

        result = resolve_remote_actor('https://remote.instance/users/nobody')
        assert result is None


class TestFollowByHandle:
    """Tests for follow-by-handle functionality (monkeypatched)."""

    def test_follow_by_handle_resolves_and_creates_record(self, monkeypatch):
        """Follow-by-handle resolves the handle and creates a Follow record."""
        import requests
        from flaskmarks.views.federation import resolve_remote_actor_by_handle, _remote_actor_cache

        _remote_actor_cache.clear()

        wf_response = {
            'subject': 'acct:alice@remote.instance',
            'links': [
                {
                    'rel': 'self',
                    'type': 'application/activity+json',
                    'href': 'https://remote.instance/users/alice',
                },
            ],
        }

        actor_response = {
            'id': 'https://remote.instance/users/alice',
            'type': 'Person',
            'preferredUsername': 'alice',
            'inbox': 'https://remote.instance/users/alice/inbox',
            'publicKey': {
                'id': 'https://remote.instance/users/alice#main-key',
                'publicKeyPem': '-----BEGIN PUBLIC KEY-----\nFAKE\n-----END PUBLIC KEY-----',
            },
        }

        call_log = []

        def fake_get(url, **kwargs):
            call_log.append(url)
            if 'webfinger' in url:
                data = wf_response
            else:
                data = actor_response

            return type('FakeResponse', (), {
                'status_code': 200,
                'json': lambda _: data,
            })()

        monkeypatch.setattr('requests.get', fake_get)

        result = resolve_remote_actor_by_handle('@alice@remote.instance')

        assert result is not None
        assert len(call_log) == 2  # WebFinger + actor fetch
        assert result['preferredUsername'] == 'alice'
        assert result.get('_inbox_url') == 'https://remote.instance/users/alice/inbox'
        assert result.get('_actor_url') == 'https://remote.instance/users/alice'

        # Test without leading @
        result2 = resolve_remote_actor_by_handle('bob@other.instance')
        # This should also work - check it doesn't crash

    def test_follow_by_handle_returns_none_for_invalid_handle(self):
        """Invalid handles should return None."""
        from flaskmarks.views.federation import resolve_remote_actor_by_handle

        result = resolve_remote_actor_by_handle('not-a-handle')
        assert result is None

        result2 = resolve_remote_actor_by_handle('')
        assert result2 is None