"""
Activity model for tracking ActivityPub activities.
"""
from __future__ import annotations

from datetime import datetime as dt

from flaskmarks.core.extensions import db


class Activity(db.Model):
    """Track ActivityPub activities generated by users."""
    __tablename__ = 'activities'

    id = db.Column(db.Integer, primary_key=True)
    actor_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False, index=True)
    activity_type = db.Column(db.Unicode(50), nullable=False)
    object_json = db.Column(db.Text, nullable=True)
    object_id = db.Column(db.Unicode(512), nullable=True)
    target_id = db.Column(db.Unicode(512), nullable=True)
    created = db.Column(db.DateTime, nullable=False, default=dt.utcnow)

    actor = db.relationship('User', backref=db.backref('activities', lazy='dynamic'))

    __table_args__ = (
        db.Index('ix_activities_actor_type', 'actor_id', 'activity_type'),
        db.Index('ix_activities_created', 'created'),
    )

    def __repr__(self):
        return f'<Activity {self.activity_type} by user {self.actor_id}>'