"""add fulltext search index

Revision ID: 3da329c515c1
Revises: dc6ff83528da
Create Date: 2026-01-02 14:25:17.197924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da329c515c1'
down_revision = 'dc6ff83528da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('idx_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_index('idx_search_vector', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
