"""Initial migration

Revision ID: dc6ff83528da
Revises: 
Create Date: 2026-01-02 14:05:51.091866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6ff83528da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('password', sa.Unicode(length=255), nullable=False),
    sa.Column('last_logged', sa.DateTime(), nullable=True),
    sa.Column('per_page', sa.SmallInteger(), nullable=True),
    sa.Column('sort_type', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Unicode(length=255), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('full_html', sa.Text(), nullable=True),
    sa.Column('url', sa.Unicode(length=512), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('last_clicked', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks_tags',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['marks.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks_tags')
    op.drop_table('marks')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
