"""Add theme field to users

Revision ID: fb1d465c762b
Revises: a1b2c3d4e5f6
Create Date: 2026-01-03 21:07:54.444203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1d465c762b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('marks', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_marks_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    #     batch_op.drop_index(batch_op.f('idx_marks_search'), postgresql_using='gin')
    #     batch_op.create_index('idx_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Unicode(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # with op.batch_alter_table('marks', schema=None) as batch_op:
    #     batch_op.drop_index('idx_search_vector', postgresql_using='gin')
    #     batch_op.create_index(batch_op.f('idx_marks_search'), ['search_vector'], unique=False, postgresql_using='gin')
    #     batch_op.create_index(batch_op.f('idx_marks_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    # ### end Alembic commands ###
